name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Build
      run: dotnet build --configuration Release "template/Service.AssetsDictionary.sln"
    - name: Test
      run: dotnet test --no-build --configuration Release "template/Service.AssetsDictionary.sln"
